version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: '03:00'
      timezone: "Asia/Shanghai"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: '04:00'
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 2